lang: zh-CN
title: Jekyll Theme ACG
description: An awesome theme for Jekyll.

author: Coder Zhao
email: coderzhaoziwei@outlook.com
github_id: coderzhaoziwei

# Theme Name
theme: jekyll-theme-acg

# Theme Color
# Default: red
# Options: red, blue, pink, green, yellow, purple
color: red

url:
baseurl:

# Theme Background Image Path
# Default: /assets/images/bg.png
# Author: saino
# Origin: https://www.pixiv.net/artworks/86925095
themeBackground:



show_excerpt: true
paginate: 10
paginate_path: /page:num

# ========== ========== ========== ========== ==========

source: "source"
destination: ".bundle"

data_dir: "_data"         # /source/_data
layouts_dir: "_layouts"   # /source/_layouts
includes_dir: "_includes" # /source/_includes
plugins_dir: ["_plugins"] # /source/_plugins

sass:
  sass_dir: _sass
  style: compressed

collections_dir: "" # /source
collections:
  posts:
    output: true

defaults:
- scope:
    path: "" # all files in the project
  values:
    layout: default
- scope:
    path: ""
    type: posts
  values:
    layout: post

plugins:
- jekyll-gist
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
- jekyll-spaceship

# Configuration for plugin: jekyll-spaceship
# @see https://github.com/jeffreytse/jekyll-spaceship#usage
jekyll-spaceship:
  processors:
    - table-processor
    - mathjax-processor
    - plantuml-processor
    - mermaid-processor
    - polyfill-processor
    - media-processor
    - emoji-processor
    - element-processor
  mathjax-processor:
    src:
      - https://polyfill.io/v3/polyfill.min.js?features=es6
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    config:
      tex:
        inlineMath:
          - ['$','$']
          - ['\(','\)']
        displayMath:
          - ['$$','$$']
          - ['\[','\]']
      svg:
        fontCache: 'global'
    optimize: # optimization on building stage to check and add mathjax scripts
      enabled: true # value `false` for adding to all pages
      include: []   # include patterns for math expressions checking (regexp)
      exclude: []   # exclude patterns for math expressions checking (regexp)
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: 'plantuml!'
      custom: ['@startuml', '@enduml']
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: 'mermaid!'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: 'media-{id}'
      class: 'media'
      width: '100%'
      height: 350
      frameborder: 0
      style: 'max-width: 600px; outline: none;'
      allow: 'encrypted-media; picture-in-picture'
  emoji-processor:
    css:
      class: emoji
    src: https://github.githubassets.com/images/icons/emoji/
