url:
baseurl:
title: Jekyll Theme ACG
description: An awesome theme for Jekyll.
author: Coder Zhao
lang: en-US
# Theme Name
theme: jekyll-theme-acg


acg:
  # Theme Color
  # Default: red
  # Options: red, blue, pink, green, yellow, purple, gray
  color:
  # Theme Background Image Path
  # Default: https://cdn.jsdelivr.net/gh/coderzhaoziwei/jekyll-theme-acg/assets/images/pixiv86925095.png
  background:
  categories:
    label: Categories
    description:
  tags:
    label: Tags
    description:
  about:
    label: About
    description:
  friends:
    label: Friends
    description:
  error:
    label: <span class="text-6xl">404</span>
    description: "Page not found."


exclude: [
  "LICENSE",
  "README.md",
  "package.json",
  "tailwind.config.js",
  "yarn.lock",
  "*.gem",
  "*.gemspec",
]


defaults:
- scope:                    # all
    path: ""
  values:
    layout: page
- scope:
    path: "index.html"
  values:
    layout: page
    type: home
- scope:                    # _posts
    path: ""
    type: posts
  values:
    layout: page
    permalink: /posts/:title
    type: post


paginate: 10
show_excerpt: true
paginate_path: /page:num
sass:
  style: compressed


# ************************************************ #
#                                                  #
#  Jekyll Archives                                 #
#                                                  #
#  @see https://github.com/jekyll/jekyll-archives  #
#                                                  #
# ************************************************ #
jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: page
    tag: page
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/


# ***************************************************** #
#                                                       #
#  Jekyll Spaceship                                     #
#                                                       #
#  @see https://github.com/jeffreytse/jekyll-spaceship  #
#                                                       #
# ***************************************************** #
jekyll-spaceship:
  processors:
    - table-processor
    - plantuml-processor
    - mermaid-processor
    - media-processor
    - emoji-processor
    - element-processor
  plantuml-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: plantuml
    syntax:
      code: "plantuml!"
      custom: ["@startuml", "@enduml"]
    src: http://www.plantuml.com/plantuml/svg/
  mermaid-processor:
    mode: default  # mode value 'pre-fetch' for fetching image at building stage
    css:
      class: mermaid
    syntax:
      code: "mermaid!"
      custom: ["@startmermaid", "@endmermaid"]
    config:
      theme: default
    src: https://mermaid.ink/svg/
  media-processor:
    default:
      id: "media-{id}"
      class: "media"
      width: "100%"
      height: 350
      frameborder: 0
      style: "max-width: 600px; outline: none;"
      allow: "encrypted-media; picture-in-picture"
  emoji-processor:
    css:
      class: emoji
    # src: https://github.githubassets.com/images/icons/emoji/
